# Generated by Django 5.2.1 on 2025-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_diagnostico_consulta_alter_diagnostico_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='indicaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
