# Generated by Django 5.2.1 on 2025-08-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Examen',
                'verbose_name_plural': 'Tipos de Examen',
            },
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('fecha_resultado', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('interpretacion_medica', models.TextField(blank=True, null=True)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='examenes/')),
                ('diagnostico_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.diagnostico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_solicitados', to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='api.paciente')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoexamen')),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
