# Generated by Django 5.2.1 on 2025-08-14 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tipoexamen_examenmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
