# Generated by Django 5.2.1 on 2025-08-18 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medico_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedades_cronicas', models.TextField(blank=True, help_text='Diabetes, hipertensión, asma, etc.', null=True)),
                ('cirugias_previas', models.TextField(blank=True, help_text='Apéndice, cesárea, etc.', null=True)),
                ('alergias', models.TextField(blank=True, help_text='Medicamentos, alimentos, etc.', null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que toma actualmente', null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Enfermedades en familiares directos', null=True)),
                ('fuma', models.BooleanField(default=False)),
                ('paquetes_por_dia', models.CharField(blank=True, max_length=10, null=True)),
                ('alcohol', models.CharField(choices=[('nunca', 'Nunca'), ('ocasional', 'Ocasional'), ('frecuente', 'Frecuente')], default='nunca', max_length=20)),
                ('ejercicio', models.CharField(blank=True, help_text='Frecuencia y tipo de ejercicio', max_length=50, null=True)),
                ('dieta', models.CharField(blank=True, help_text='Dieta habitual', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='api.paciente')),
            ],
            options={
                'verbose_name': 'Antecedente Médico',
                'verbose_name_plural': 'Antecedentes Médicos',
            },
        ),
    ]
