# Generated by Django 5.2.1 on 2025-08-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
