# Generated by Django 5.2.1 on 2025-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial o razón social del consultorio', max_length=100, verbose_name='Nombre o Razón Social')),
                ('rif', models.CharField(help_text='Ej: J-12345678-9', max_length=20, unique=True, verbose_name='RIF')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('logo', models.ImageField(blank=True, help_text='Logo del consultorio (opcional)', null=True, upload_to='logos/', verbose_name='Logo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este consultorio es el activo para el sistema')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
            },
        ),
    ]
